
title: Syea for future

email: 244843347@qq.com

baseurl: "" 

url: ""  

author: Wang Jiawei

author_zh-CN: 王嘉威

timezone: Asia/Shanghai

twitter_username:

github_username: 
  
sina_username: 

exclude: [
  "README.md"
]

port: 4000
