# Site settings
title: Syea Blog
SEOTitle: Syea
header-img: img/home-bg.jpg
email: email@email.com
description: "config.descripetion"
keyword: "iOS Objective-C React Syea Blog China"
url: "https://mr-yo.github.io"      
baseurl: ""                      



# SNS settings
RSS: false
weibo_username:  3292010391    
github_username:   MR-yo
twitter_username:   Jiawei_Hope



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true



# Gems
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
   input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: 一只小火龙

# Netease setttings
netease_comment: false


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "安静地写代码"
sidebar-avatar: /img/headImage.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



